### ISSUE TITLE
Current Weather is Not Wroking

### ISSUE THREAD

**Issue by shivanagendrakore** [sandeepgantasala/Breezy#3]
<img width="1093" alt="Screenshot 2024-12-03 at 1 29 24 PM" src="https://github.com/user-attachments/assets/5b59c27f-1a7c-4d58-bc09-9a391c2f73eb">

**Comment by sandeepgantasala** [comment]
"Resolved Issue"

**Comment by sandeepgantasala** [comment]
"Issue Resolved"
